name: Deploy to Render

on:
  push:
    branches:
      - main  # или твоя рабочая ветка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install

    - name: Export requirements.txt
      run: |
        poetry export -f requirements.txt --without-hashes > requirements.txt

    - name: Deploy to Render
      run: |
        # команда для деплоя, например:
        render deploy  # если у тебя настроено через Render CLI
